import "./globals.css";

import Footer from "@/components/layouts/Footer";
import Navbar from "@/components/layouts/Navbar";
import NextAuthProvider from "@/provider/NextAuthProvider";

export const metadata = {
  title: "Hero Kidz",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <NextAuthProvider>
      <html lang="en">
        <body className="flex flex-col min-h-screen">
          <Navbar></Navbar>
          <main className="flex-grow">{children}</main>
          <Footer></Footer>
        </body>
      </html>
    </NextAuthProvider>
  );
}
